5-11-extern: 5-11-extern1.o 5-11-extern2.o
	g++ -o 5-11-extern 5-11-extern1.o 5-11-extern2.o

5-11-extern1.o: 5-11-extern1.cpp
	g++ -c 5-11-extern1.cpp

5-11-extern2.o: 5-11-extern2.cpp
	g++ -c 5-11-extern2.cpp


