
Override2: Override2.o Stream.o InputStream.o ArrayStream.o
	g++ -o Override2 Override2.o Stream.o InputStream.o ArrayStream.o
Stream.o: Stream.cpp
	g++ -c Stream.cpp
ArrayStream.o: ArrayStream.cpp
	g++ -c ArrayStream.cpp
InputStream.o: InputStream.cpp
	g++ -c InputStream.cpp
Override2.o: Override2.cpp
	g++ -c Override2.cpp
