
Override3: Override3.o Stream.o InputStream.o
	g++ -o Override3 Override3.o Stream.o InputStream.o
Stream.o: Stream.cpp
	g++ -c Stream.cpp
InputStream.o: InputStream.cpp
	g++ -c InputStream.cpp
Override3.o: Override3.cpp
	g++ -c Override3.cpp
